CREATE TABLE budgets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id   BIGINT,
    limit_amount  DECIMAL                                 NOT NULL,
    spent_amount  DECIMAL                                 NOT NULL,
    budget_status VARCHAR(255),
    year          INTEGER                                 NOT NULL,
    month         INTEGER                                 NOT NULL,
    user_id       BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_budgets PRIMARY KEY (id)
);

ALTER TABLE budgets
    ADD CONSTRAINT FK_BUDGETS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE budgets
    ADD CONSTRAINT FK_BUDGETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);