CREATE TABLE budget_alerts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    user_id    BIGINT,
    budget_id  BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_budget_alerts PRIMARY KEY (id)
);

ALTER TABLE budget_alerts
    ADD CONSTRAINT FK_BUDGET_ALERTS_ON_BUDGET FOREIGN KEY (budget_id) REFERENCES budgets (id);

ALTER TABLE budget_alerts
    ADD CONSTRAINT FK_BUDGET_ALERTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);