CREATE TABLE audit_log
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    message     VARCHAR(255),
    action      VARCHAR(255)                            NOT NULL,
    entity_type VARCHAR(255)                            NOT NULL,
    entity_id   BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);

ALTER TABLE audit_log
    ADD CONSTRAINT FK_AUDIT_LOG_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);